### ISSUE TITLE
No such file or directory: '/sys/class/net/'

### ISSUE THREAD

**Issue by Amychan-air** [ZKAW/wifi-deauther#2]
Hi I don’t know if you are still maintaining this program

I think
1. Many users have not installed scapy. I think I need to remind you to install it.
2. In w-killer.py line 38 to 40, I think these data should be placed in your main folder, WIFI-FILLER.

**Comment by Amychan-air** [comment]
I can't use this program
I am using Mac intal, python3.8
<img width="743" alt="螢幕截圖 2021-04-12 下午5 45 19" src="https://user-images.githubusercontent.com/78076780/114375035-db44bb80-9bb6-11eb-8fab-0085af252552.png">

**Comment by Amychan-air** [comment]
I checked your codek and I found some problems.
1. In the Install program, I can't see any builds: /sys/class/net/ If you can, please tell me

2. But in W-killer.py you will use this file

**Comment by Amychan-air** [comment]
I am using Google Translate to communicate with you and hope we can solve this problem.If you don’t understand, please ask

**Comment by ZKAW** [comment]
Hey, sorry for the late reply,

I just checked your report and it comes from aircrack itself. /sys/class/ net is a directory used by aircrack. The error can therefore come from a missing administrator privilege.
Please make sure to run the script in admin mod with `sudo python3 W-Killer.py` and come back to me if the error persists.

Regarding Scapy, It is automatically downloaded with the INSTALL program. If that doesn't work for you, you can install it manually with `pip3 install scapy`

One thing that could cause the issue is that the program is made for Linux and you are using Mac/OS.

Best regards.
